### ISSUE TITLE
FetchEnvs isnt maintaining defined order of envs

### ISSUE THREAD

**Issue by alewitt2** [razee-io/razeedeploy-core#116]
**Describe the bug**
FetchEnvs is supposed to fetch envs in the order they are defined. This must be deterministic in order to allow a user to create overrides.

**To Reproduce**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-versions
  namespace: default
data:
  serviceA: 1.2.3
  serviceB: 2.0.3
  serviceC: 1.0.1
  serviceD: 5.0.1
  serviceE: 3.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wave-versions
  namespace: default
data:
  serviceA: 1.5.0
  serviceC: 2.0.1
  serviceD: 6.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-versions
  namespace: default
data:
  serviceB: 5.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-versions
  namespace: default
data:
  serviceA: 2.0.1
  serviceB: 3.0.5
---
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  annotations:
  labels:
    app: override-versions
    razee/watch-resource: lite
  name: override-versions
  namespace: default
spec:
  envFrom:
  - configMapRef:
      name: global-versions
  - configMapRef:
      name: wave-versions
  - configMapRef:
      name: common-versions
  - configMapRef:
      name: local-versions
  templates:
  - apiVersion: v1
    data:
      serviceA: '{{serviceA}}'
      serviceB: '{{serviceB}}'
      serviceC: '{{serviceC}}'
      serviceD: '{{serviceD}}'
      serviceE: '{{serviceE}}'
    kind: ConfigMap
    metadata:
      name: override-versions
```

```
$ k get configmap override-versions -o json | jq ".data"
{
  "serviceA": "2.0.1",
  "serviceB": "5.0.1",
  "serviceC": "1.0.1",
  "serviceD": "5.0.1",
  "serviceE": "3.0.1"
}
$ k delete cm override-versions
configmap "override-versions" deleted
$ k get configmap override-versions -o json | jq ".data"
{
  "serviceA": "2.0.1",
  "serviceB": "3.0.5",
  "serviceC": "2.0.1",
  "serviceD": "6.0.1",
  "serviceE": "3.0.1"
}
```

**Expected behavior**
The result should always be the same, where the last defined env overrides previous ones.

**How to Fix**
instead of pushing the results to an array, we should be returning the results to the promise, and then using the Promise.all() returned array as the result.

https://github.com/razee-io/razeedeploy-core/blob/master/lib/FetchEnvs.js#L114
https://github.com/razee-io/razeedeploy-core/blob/master/lib/FetchEnvs.js#L183

https://github.com/razee-io/razeedeploy-core/blob/master/lib/FetchEnvs.js#L200
https://github.com/razee-io/razeedeploy-core/blob/master/lib/FetchEnvs.js#L218
