### ISSUE TITLE
Allow fetchEnvs to pull data from json strings

### ISSUE THREAD

**Issue by alewitt2** [razee-io/razeedeploy-core#125]
**Is your feature request related to a problem? Please describe.**
currently there is no way to get data from inside a json string defined in a cm. you can specify type: json, but that only parses the json and leaves its keys as a second class citizen.

**Describe the solution you'd like**
give a way to pull a single key or all the keys from a json into the top level of the returned fetchEnvs obj.

**Describe alternatives you've considered**
use fetchEnvs to get the json, then do post processing on the returned object to flatten accordingly

**Additional context**

---
example configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-system
data:
  cluster-config: |
    {
      "cluster_id": "1234",
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
```

a normal example of using `.env` in razee
```yaml
env
  - name: cluster-config # name of the key the fetched data will be assigned to
    valueFrom:
      configMapKeyRef:
        key: cluster-config # key within configmap
        name: cluster-info # configmap name
        namespace: kube-system # configmap namespace
        type: json # tells fetchEnvs to parse the fetched key
```

with a result of
```json
{
  "cluster-config":
    {
      "cluster_id": "1234",
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
}
```

---

example configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-system
data:
  cluster-config: |
    {
      "cluster_id": "1234",
      "cluster_metadata": {
          "created": "sometimelastweek"
        },
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
```

example of using `.env` and being able to specify the path to a lower level json key
```yaml
env:
  - name: cluster_created # name of key retrieved data will be assigned to
    valueFrom:
      configMapKeyRef:
        key: cluster-config # key within configmap
        name: cluster-info # configmap name
        namespace: kube-system # configmap namespace
        type: json # tells fetchEnvs to parse the fetched key
        pathStr: 'cluster_metadata.created' # must have type defined
```

with a result of
```json
{
  "cluster_created": "sometimelastweek"
}
```

---

example configmap with `.` in key name
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-system
data:
  cluster-config: |
    {
      "cluster_id": "1234",
      "cluster.metadata": {
          "created": "sometimelastweek"
        },
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
```

example of using `.env` and being able to specify the path to a lower level json key
```yaml
env:
  - name: cluster_created # name of key retrieved data will be assigned to
    valueFrom:
      configMapKeyRef:
        key: cluster-config# key within configmap
        name: cluster-info # configmap name
        namespace: kube-system # configmap namespace
        type: json # tells fetchEnvs to parse the fetched key
        path: ['cluster.metadata', 'created'] # must have type defined
```

with a result of
```json
{
  "cluster_created": "sometimelastweek"
}
```

---

example configmap 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-system
data:
  cluster-config: |
    {
      "cluster_id": "1234",
      "cluster_metadata": {
          "created": "sometimelastweek"
        },
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
```

example of using `.env` and being able to specify the path to get all json items
```yaml
env:
  - name: cluster_created # not used when path all `.` is defined
    valueFrom:
      configMapKeyRef:
        key: cluster-config # key within configmap
        name: cluster-info # configmap name
        namespace: kube-system # configmap namespace
        type: json # tells fetchEnvs to parse the fetched key
        pathStr: '.' # must have type defined
```

with a result of
```json
    {
      "cluster_id": "1234",
      "cluster_metadata": {
          "created": "sometimelastweek"
        },
      "cluster_name": "dev-mexico",
      "cluster_type": "dev"
    }
```
