### ISSUE TITLE
BaseController (reconcileFields) throws error if apply an "empty" configmap template to a "non-empty" configmap 

### ISSUE THREAD

**Issue by david-shepard** [razee-io/razeedeploy-core#152]
**Describe the bug**
This is a tricky corner case bug I've been running into dealing with the reconcileFields snippet https://github.com/razee-io/razeedeploy-core/blob/master/lib/BaseController.js#L482-L494. If the loop 
```js
Object.keys(lastApplied).forEach(key => {
  let path = clone(parentPath);
  path.push(key);
  if (!objectPath.has(config, path)) {
    objectPath.set(config, path, null);
  } else if (lastApplied[key] && typeof lastApplied[key] == 'object' && !Array.isArray(lastApplied[key])) {
    this.reconcileFields(config, lastApplied[key], path);
  }
});
```
 contains a `path` from that isn't resolvable from the `config`, `objectPath` will attempt to `set` a `null` field throwing an error. This can occur if a `config`/`configmap` has an empty `data` field and a `last-applied-configuration` with defined values for `data` ie.

```yaml
apiVersion: v1
data:

kind: ConfigMap
metadata:
  annotations:
    deploy.razee.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"handlebars-config","namespace":"cpdaas-cluster-config"},"data":{"version":"v1"}}'
```
In my experience this most commonly occurs if you have a defined `data` field, and then template it in such a way that the `data` field becomes empty. See below for more details:

**To Reproduce**
1. Apply the following YAML notice the ConfigMap will have a **defined** value for `data`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    razee/watch-resource: detail
  name: test-configmap
data:
  KEY: some_value
---
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  name: mustache-test
spec:
  templateEngine: 'mustache'
  envFrom:
    - configMapRef:
        apiVersion: v1
        name: test-configmap
  strTemplates:
  - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mustache-config
      data:
        {{#KEY}}
        "version": {{ KEY}}
        {{/KEY}}
```
2. Then reconfigure the `mustache-test` yaml to look like this, notice the `data` field _should_ be empty when the mustache-config is rendered, but the `reconcileFields` loop errors out since the last-applied-configuration had a defined `data.version: some_value`

```yaml
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  name: mustache-test
spec:
  templateEngine: 'mustache'
  envFrom:
    - configMapRef:
        apiVersion: v1
        name: test-configmap
  strTemplates:
  - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mustache-config
      data:
        {{#KEY_DNE}}
        "version": {{ KEY}}
        {{/KEY_DNE}}
```
3. You should receive a ```ConfigMap.v1 "mustache-config" status undefined .. see logs for details``` error and if you look at the logs you'll see something like ```"message":"Cannot set property 'version' of null"```

**Expected behavior**
No errors, a resulting configmap with an empty data field

**Additional context**
This took a longggg time to debug ;)

It can be fixed in a few ways - first thing that jumps to mind is 
```js
  if ( (!objectPath.has(config, path)) && objectPath.has(config, path.slice(0,-1)) ) // { .. }
```
cc @alewitt2 we were talking about this earlier
