### ISSUE TITLE
Allow FetchEnvs to pull data from anywhere on a resource

### ISSUE THREAD

**Issue by alewitt2** [razee-io/razeedeploy-core#251]
The base case im trying to solve with this is to allow a mustache template pull the resorceVersion from a cm/secret's metadata so that we can restart a deployment when it changes.

Some users might want to grab whole json objects or boolean values. In this case we probably need a way to convert them into a string, so a new string `type` should be added to do the `.toString()` to the value if needed.

ex:
```
env:
  - name: rv # name of the key the fetched data will be assigned to
    valueFrom:
      configMapKeyRef:
        path: metadata.resourceVersion # path to key within configmap
        name: cluster-info # configmap name
        namespace: kube-system # configmap namespace
        type: string # tells fetchEnvs to stringify the fetched key if its not already
```
