### ISSUE TITLE
FetchEnvs does not differentiate between network error and config map not found

### ISSUE THREAD

**Issue by evanlucas** [razee-io/razeedeploy-core#300]
If I have the following MustacheTemplate:

```yaml
---
apiVersion: "deploy.razee.io/v1alpha2"
kind: MustacheTemplate
metadata:
  name: biscuits
  namespace: default
  labels:
    app: biscuits
    razee/watch-resource: 'debug'
spec:
  env:
  - name: enabled_storage_provider_a
    optional: true
    default: ''
    valueFrom:
      configMapKeyRef:
        key: enabled_storage_provider_a
        name: storage
  strTemplates:
  - |
    apiVersion: v1
    kind: List
    items:
    - apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: biscuits
        labels:
          app: biscuits
      spec:
        serviceName: biscuits
        podManagementPolicy: "Parallel"
        updateStrategy:
          type: RollingUpdate

        selector:
          matchLabels:
            app: biscuits

        template:
          metadata:
            annotations:
              {{#enabled_storage_provider_a}}stork.libopenstorage.org/preferLocalNodeOnly: "true"{{/enabled_storage_provider_a}}

```

In some environments, I might have `enabled_storage_provider_a` be an empty string, and in others, it might be `"true"`. If a network error occurs when fetching the config map value, it is assumed that the value does not exist, which will make it use the default value here. This will create a new StatefulSet with the annotations (we use this same method to set environment variables)

**To Reproduce**
It's hard to reproduce since it seems to only occur for us when a network error occurs.

**Expected behavior**
I would expect the processing of the current resource to stop and an error be logged?

**Kubernetes Version (kubectl version):**
 - Client: 1.22.4
 - Server: 1.21.5

**Additional context**
This is problematic because it ends up creating a new stateful set and starts rolling it out (sometimes with default, but incorrect configuration). Then, when the network issues subside, the correct configuration will be re-applied, rolling the entire set of applications again.

I'm happy to provide any additional information if needed. Thanks!
